# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48be8a13cd427f580a95e14a6491bdec508544cc8f6649a92f8e37af1d98a44b2f24c77f4371bd7789146a4ab2de843528672568d6af9a3abf354afb7797d15f

test:
  secret_key_base: ffd7e957f9df96dd7357bda9c15b97f1fc1cd3fe7a9d4842c6d011afede310ad9eab082274a0ec783aa7fd5d80e856aa52e86b5bdfc561b27687705dbcafecda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
